[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# Compiler Settings
solc = '0.8.28'                # Solidity compiler version
optimizer = true               # Enable optimizer
optimizer_runs = 222
via_ir = true                  # Enable viaIR
extra_output = ["ir", "irOptimized"]
